feature/TS-3-integrate-analytics-and-crashlytics
Shop-G/ShopGo pull request #11
Opened 2022-09-22 01:04 UTC by humzacheema

## jira
[TS-3](https://shop-go.atlassian.net/browse/TS-3)

Description:
* Integrated Analytics and Crashlytics.
* Crashes and log events will be logged in firebase.

How to test it?
* call FatalError() in viewDidLoad(), once the app crashes pause the app and reopen the app on stimulator.
* Make an IBaction button and call this method in it Analytics.logEvent("button_pressed", parameters: nil).

ScreenShots&Gifs:
<img width="561" alt="Screen Shot 2022-09-20 at 5 37 15 PM" src="https://user-images.githubusercontent.com/113794795/191369634-e2ec56e7-d542-421e-ab59-962f9124bfaf.png">

2022-09-22 01:28 UTC, basitalich requested changes

2022-09-22 01:28 UTC, basitalich commented on ShopGo/Base.lproj/Main.storyboard
> -                        <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
What changes are made on main story board?

2022-09-22 01:28 UTC, basitalich commented on ShopGo/ViewController.swift
> -        super.viewDidLoad()
why you removed super.viewdidload()?

2022-09-22 01:28 UTC, basitalich commented on ShopGoTests/ShopGoTests.swift
> -@testable import ShopGo
why this is removed?

2022-09-22 02:06 UTC, humzacheema commented on ShopGo/Base.lproj/Main.storyboard
> -                        <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
rechecked no changes are made which are visual

2022-09-22 02:07 UTC, humzacheema commented on ShopGoTests/ShopGoTests.swift
> -@testable import ShopGo
removed it after checking for errors

2022-09-22 02:19 UTC, basitalich commented on ShopGo/Base.lproj/Main.storyboard
> -                        <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
Then why this file is showing changes?

2022-09-24 08:36 UTC, basitalich approved these changes

2022-09-24 20:30 UTC, basitalich submitted a review, later dismissed

2022-09-24 20:31 UTC, haroonmaqsoodch approved these changes

2022-09-24 21:16 UTC, haroonmaqsoodch approved these changes

2022-09-24 21:17 UTC, basitalich approved these changes

2022-09-24 21:17 UTC, merged