[TS-14]: build logic for log in screen
Shop-G/ShopGo pull request #18
Opened 2022-09-29 17:40 UTC by zuhair5

## jira

[TS-14](https://shop-go.atlassian.net/browse/TS-14)

Description

- Implement username and password validation
- Password should be secure entry text, should not be visible all the time
- Password must have a special character and a number and no emoji
- If the wrong password is entered, shake the text field (left-right) and change the field’s border color to red

How to Test?

- in info.plist change the storyboard name to LoginScreen

2022-09-29 18:18 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +        }else{
space before else and after else

2022-09-29 18:19 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +        }else{
same space issue

2022-09-29 18:19 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +        print("return")
remove all the print statements

2022-09-29 18:19 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +extension LoginVC{
space before curly brace

2022-09-29 18:20 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +            }else{
same

2022-09-29 18:20 UTC, haroonmaqsoodch commented on ShopGo/LoginVC.swift
> +    }
make a separate file name it "Textfield+extension" and move this from here

2022-09-29 18:22 UTC, haroonmaqsoodch reviewed
If we type one word in the password field the login button still gets enabled even tho we need to enforce the user to have special character and number

2022-09-30 01:39 UTC, basitalich requested changes

2022-09-30 01:39 UTC, basitalich commented on ShopGo/LoginVC.swift
Conform the textfield delegate in extension and separate the code for textfield over there.

2022-09-30 01:39 UTC, basitalich commented on ShopGo/LoginVC.swift
> +        if (isValidUsername(username: usernameField!)) && usernameField == username {
Clean these conditions, they are looking weird.

2022-09-30 10:31 UTC, zuhair5 commented on ShopGo/LoginVC.swift
resolved

2022-09-30 10:32 UTC, zuhair5 commented on ShopGo/LoginVC.swift
> +        if (isValidUsername(username: usernameField!)) && usernameField == username {
resolved

2022-09-30 19:17 UTC, MuhammadHuzaifa2 approved these changes

2022-10-01 02:57 UTC, merged