built term and conditions screen
Shop-G/ShopGo pull request #3
Opened 2022-09-21 01:42 UTC by ayeshaalyas

##jira
[feature/TS-8-build-terms-conditions-screen](https://github.com/Shop-G/ShopGo/compare/develop...feature/TS-8-build-terms-conditions-screen?expand=1)

Description:
-> build the UI for terms and condition screen
-> click on read more button will extend label text and and also change title and vice versa

2022-09-21 04:19 UTC, haroonmaqsoodch commented on TermsAndConditions/TermsAndConditionVC.swift
> +    var isReadMoreTapped = false
move var above the the outlets

2022-09-21 04:20 UTC, haroonmaqsoodch commented on TermsAndConditions/TermsAndConditionVC.swift
> +
remove extra space from viewDidLoad()

2022-09-21 04:20 UTC, haroonmaqsoodch commented on TermsAndConditions/TermsAndConditionVC.swift
> +        }else {
one space before else

2022-09-21 04:24 UTC, haroonmaqsoodch commented on TermsAndConditions/TermsAndConditionVC.swift
> +//
move your swift file and storyboard file out of the folder with other ViewController and main storyboard. Delete the group after you move them

2022-09-21 06:30 UTC, haroonmaqsoodch reviewed
There is no show less button in the design, the chevron should move to the right side in order to make the text "less" please fix this change as per design

2022-09-21 13:06 UTC, ayeshaalyas commented
okay

On Wed, Sep 21, 2022 at 1:30 AM haroonmaqsoodch ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> There is no show less button in the design, the chevron should move to the
> right side in order to make the text "less" please fix this change as per
> design
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Shop-G/ShopGo/pull/3#pullrequestreview-1114824594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3EGHIVDCI3GG5C7OUMMSOLV7KTRZANCNFSM6AAAAAAQRTO27I>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-22 01:30 UTC, basitalich requested changes

2022-09-22 01:41 UTC, basitalich requested changes

2022-09-22 01:41 UTC, basitalich commented on TermsAndConditions/TermsAndConditionVC.swift
> +        if isReadMoreTapped {
fix indentation and spacing

2022-09-22 02:48 UTC, ayeshaalyas commented on TermsAndConditions/TermsAndConditionVC.swift
> +    @IBOutlet weak var textLablel: UILabel!
i am using a label inside a view to display text

2022-09-22 02:49 UTC, ayeshaalyas commented on TermsAndConditions/TermsAndConditionVC.swift
> +
i removed spaces

2022-09-22 02:56 UTC, ayeshaalyas commented on TermsAndConditions/TermsAndConditionVC.swift
> +        if isReadMoreTapped {
i did

2022-09-24 20:21 UTC, basitalich approved these changes

2022-09-24 20:21 UTC, merged