[TS-9]: build create account screen
Shop-G/ShopGo pull request #8
Opened 2022-09-21 20:50 UTC by AnoshaKhan

## jira

### Feature/TS-9-build-create-account-screen 

#### Description:
-> build the UI for create account screen

2022-09-21 22:27 UTC, Harrisali93 commented on ShopGo/CreateScreenViewController.swift
> +    func updateLayerProperties(){
add a space after function type

2022-09-21 22:28 UTC, Harrisali93 commented on ShopGo/CreateScreenViewController.swift
> +
remove unnecessary spaces

2022-09-21 22:28 UTC, Harrisali93 commented on ShopGo/logInViewController.swift
> +//        let userNameImage = UIImage(named: "")
remove all the commented lines

2022-09-21 22:46 UTC, Harrisali93 commented on ShopGo/CreateScreenViewController.swift
> +
lines*

2022-09-22 01:38 UTC, basitalich requested changes
Add comments on top of each method.

2022-09-22 01:38 UTC, basitalich commented on ShopGo/Base.lproj/Main.storyboard
> +        <plugIn identifier="com.apple.InterfaceBuilder.IBCocoaTouchPlugin" version="21207"/>
why there are changes on main story board?

2022-09-22 01:38 UTC, basitalich commented on ShopGo/CreateScreenViewController.swift
> +    override func viewDidLoad() {
add space between outlets and viewDidLoad()

2022-09-22 01:38 UTC, basitalich commented on ShopGo/CreateScreenViewController.swift
> +//        let userNameImage = UIImage(named: "")
why commented code?

2022-09-22 01:38 UTC, basitalich commented on ShopGo/CreateScreenViewController.swift
> +        let emailImage = UIImage(named: "mail")
do this in seperate method and call it in view did load.

2022-09-22 01:38 UTC, basitalich commented on ShopGo/CreateScreenViewController.swift
> +//       let phoneNoImage = UIImage(named: "")
why comments?

2022-09-22 01:38 UTC, basitalich commented on ShopGo/logInViewController.swift
> +    override func viewDidLoad() {
add space

2022-09-22 01:38 UTC, basitalich commented on ShopGo/logInViewController.swift
> +        nextButton.layer.cornerRadius = 22
make separate method for this

2022-09-22 04:57 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +    func updateLayerProperties(){
added.

2022-09-22 04:57 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +
removed.

2022-09-22 04:57 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +    override func viewDidLoad() {
added.

2022-09-22 04:59 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +//        let userNameImage = UIImage(named: "")
cuz you guys didn't send the logos  for text fields , that's why I commented them otherwise I got  error .

2022-09-22 05:00 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +        let emailImage = UIImage(named: "mail")
done.

2022-09-22 05:00 UTC, AnoshaKhan commented on ShopGo/logInViewController.swift
> +    override func viewDidLoad() {
added.

2022-09-22 12:54 UTC, AnoshaKhan commented on ShopGo/CreateScreenViewController.swift
> +//        let userNameImage = UIImage(named: "")
decommented the code .

2022-09-24 20:27 UTC, haroonmaqsoodch approved these changes

2022-09-24 20:27 UTC, basitalich approved these changes

2022-09-24 20:27 UTC, merged