build login screen
Shop-G/ShopGo pull request #9
Opened 2022-09-21 21:21 UTC by zuhair5

## jira
[TS-7](https://shop-go.atlassian.net/browse/TS-7)

**Description:**
* Built a log-in screen.
* Autolayout has been done on all the ui elements.

**How to test it?**
* Go to info.plist and change the storyboard name to Loginscreen.

ScreenShots&Gifs:
<img width="561" alt="Screen Shot 2022-09-20 at 5 37 15 PM" src="https://user-images.githubusercontent.com/63094797/191611856-c516e86f-60d2-46c6-a1f1-cf6368cfce47.png">

2022-09-21 21:34 UTC, haroonmaqsoodch commented on ShopGo/LoginViewController.swift
> +class LoginViewController: UIViewController {
one space after class declaration

2022-09-21 21:34 UTC, haroonmaqsoodch commented on ShopGo/LoginViewController.swift
> +        addLeftImageToTextfield(textfield: usernameTextfield, addImage: usernameImage)
make a configure method and put these in that, call that method in viewDidLoad()

2022-09-22 01:33 UTC, basitalich requested changes
Add comments to each method you wrote that what it is doing.

2022-09-22 01:33 UTC, basitalich commented on ShopGo/CustomButton.swift
> +    override init(frame: CGRect) {
add space between methods.

2022-09-22 01:33 UTC, basitalich commented on ShopGo/CustomButton.swift
> +    required init?(coder aDecoder: NSCoder) {
space here

2022-09-22 01:33 UTC, basitalich commented on ShopGo/CustomButton.swift
> +    func setRadiusAndShadow() {
space here

2022-09-22 01:33 UTC, basitalich commented on ShopGo/LoginViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
space between methods and outlets.

2022-09-22 01:33 UTC, basitalich commented on ShopGo/LoginViewController.swift
> +extension LoginViewController {
space

2022-09-22 22:22 UTC, zuhair5 commented on ShopGo/CustomButton.swift
> +    override init(frame: CGRect) {
Added Spaces between methods

2022-09-22 22:22 UTC, zuhair5 commented on ShopGo/CustomButton.swift
> +    required init?(coder aDecoder: NSCoder) {
done

2022-09-22 22:23 UTC, zuhair5 commented on ShopGo/CustomButton.swift
> +    func setRadiusAndShadow() {
space given

2022-09-22 22:23 UTC, zuhair5 commented on ShopGo/LoginViewController.swift
> +    @IBOutlet weak var scrollView: UIScrollView!
space given

2022-09-22 22:24 UTC, zuhair5 commented on ShopGo/LoginViewController.swift
> +        addLeftImageToTextfield(textfield: usernameTextfield, addImage: usernameImage)
resolved

2022-09-22 22:24 UTC, zuhair5 commented on ShopGo/LoginViewController.swift
> +    @IBOutlet weak var passwordTextfield: UITextField!
resolved

2022-09-22 23:49 UTC, haroonmaqsoodch submitted a review, later dismissed

2022-09-24 08:42 UTC, basitalich approved these changes

2022-09-24 19:16 UTC, basitalich approved these changes

2022-09-24 19:17 UTC, haroonmaqsoodch approved these changes

2022-09-24 19:17 UTC, merged